import React from 'react';
import { createStackNavigator} from '@react-navigation/stack';
import {Splash,Login,Dashboard, Pegawai,AddPegawai, Client,AddClient,
        Project,AddProject,Tab,Pic,Account,DashboardP,DetailProject, 
        ProgressP, TeamP, AccountP, DashboardPM, DataPegawai,Document, 
        Task, ProgressPM, Feedback, AccountPM, DetailProjectAdmin, 
        AddMaterial, AddAlat, TeamPM, AddTeam,UploadDoc, AddTask, 
        AddFeedback
        } from '../pages';

const Stack = createStackNavigator();

const Router = () =>{
    return(
        <Stack.Navigator>
            <Stack.Screen 
                name="Login" 
                component={Login} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="Dashboard" 
                component={Dashboard} 
                options={{
                    headerShown:false,
                }}
            />
            
            <Stack.Screen 
                name="Pegawai" 
                component={Pegawai} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="AddPegawai" 
                component={AddPegawai} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="Client" 
                component={Client} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="AddClient" 
                component={AddClient} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="Project" 
                component={Project} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="AddProject" 
                component={AddProject} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="Tab" 
                component={Tab} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="Pic" 
                component={Pic} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="Account" 
                component={Account} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="DashboardP" 
                component={DashboardP} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="DetailProject" 
                component={DetailProject} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="ProgressP" 
                component={ProgressP} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="TeamP" 
                component={TeamP} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="AccountP" 
                component={AccountP} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="DashboardPM" 
                component={DashboardPM} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="DataPegawai" 
                component={DataPegawai} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="Document" 
                component={Document} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="Task" 
                component={Task} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="ProgressPM" 
                component={ProgressPM} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="Feedback" 
                component={Feedback} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="AccountPM" 
                component={AccountPM} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="DetailProjectAdmin" 
                component={DetailProjectAdmin} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="AddMaterial" 
                component={AddMaterial} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="AddAlat" 
                component={AddAlat} 
                options={{
                    headerShown:false,
                }}
            />
            
            <Stack.Screen 
                name="TeamPM" 
                component={TeamPM} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="AddTeam" 
                component={AddTeam} 
                options={{
                    headerShown:false,
                }}
            />
            
            <Stack.Screen 
                name="UploadDoc" 
                component={UploadDoc} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="AddTask" 
                component={AddTask} 
                options={{
                    headerShown:false,
                }}
            />
            <Stack.Screen 
                name="AddFeedback" 
                component={AddFeedback} 
                options={{
                    headerShown:false,
                }}
            />
                      
        </Stack.Navigator>
    );
};

export default Router;